name: consec_tcs_cli_build_and_scan_single_image
on:
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
          
      - name: Build Image
        run: |
           echo "building docker image"
           docker build -t tcs-consec:new .
      
      - name: TCS CLI Scan
        env:
          TCS_CLI_DOWNLOAD_URL: ${{ secrets.TCS_CLI_DOWNLOAD_URL }}
          TCS_TOKEN: ${{ secrets.TCS_TOKEN }}
          TCS_PROJECT_ID: ${{ secrets.TCS_PROJECT_ID }}
        
        run: |
          echo ~~~ Installation of TCS CLI ~~~
          wget $TCS_CLI_DOWNLOAD_URL
          
          file_name=`echo $TCS_CLI_DOWNLOAD_URL | cut -f10 -d "/"`
          tar -xf $file_name && chmod +x tcs
          
          echo ~~~ Starting TCS CLI Image scan ~~~
          ./tcs consec image tcs-consec:new --wait
